### ISSUE TITLE
ResNet-50.caffemodel

### ISSUE THREAD

**Issue by zhaishengfu** [eldar/deepcut#2]
Due to some reasons, I need your ResNet-50.caffemodel, Can you supply it??

**Comment by eldar** [comment]
Here you are:
http://datasets.d2.mpi-inf.mpg.de/deepercut-models/ResNet-50-mpii-multiperson.caffemodel
http://datasets.d2.mpi-inf.mpg.de/deepercut-models/ResNet-50-test.prototxt
